# Generated by Django 2.1.1 on 2018-09-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsdetails',
            name='footer',
            field=models.CharField(default='', max_length=300, verbose_name='Footer Text'),
        ),
        migrations.AlterField(
            model_name='adsdetails',
            name='header',
            field=models.CharField(default='', max_length=300, verbose_name='Header text'),
        ),
        migrations.AlterField(
            model_name='adsdetails',
            name='left_bottom',
            field=models.CharField(default='', max_length=200, verbose_name='Ad-2: Bottom Left'),
        ),
        migrations.AlterField(
            model_name='adsdetails',
            name='left_top',
            field=models.CharField(default='', max_length=200, verbose_name='Ad-1: Top Left'),
        ),
        migrations.AlterField(
            model_name='adsdetails',
            name='right_bottom',
            field=models.CharField(default='', max_length=200, verbose_name='Ad-4: Bottom Right'),
        ),
        migrations.AlterField(
            model_name='adsdetails',
            name='right_top',
            field=models.CharField(default='', max_length=200, verbose_name='Ad-3: Top Right'),
        ),
    ]
