# Generated by Django 2.1.1 on 2018-09-21 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_auto_20180921_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Name')),
                ('client_business', models.CharField(blank=True, choices=[('Mall', 'Mall'), ('Theatre', 'Theatre'), ('RE', 'Real Estate'), ('Retail', 'Retail')], default='', max_length=100, verbose_name='Business')),
                ('client_contact', models.IntegerField(blank=True, default='', max_length=15, verbose_name='Contact number')),
                ('client_email', models.CharField(blank=True, default='', max_length=50, verbose_name='Email')),
                ('client_address', models.CharField(blank=True, default='', max_length=150, verbose_name='Address')),
                ('client_locality', models.CharField(blank=True, default='', max_length=50, verbose_name='Locality')),
                ('client_city', models.CharField(blank=True, default='', max_length=50, verbose_name='City')),
                ('client_state', models.CharField(blank=True, default='', max_length=30, verbose_name='State')),
                ('client_country', models.CharField(blank=True, default='', max_length=30, verbose_name='Country')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
