# Generated by Django 2.1.1 on 2018-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_contact',
            field=models.IntegerField(blank=True, default='', max_length=15, null=True, verbose_name='Contact number'),
        ),
    ]
