# Generated by Django 2.1.1 on 2018-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180921_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsdetails',
            name='update_flag',
            field=models.BooleanField(default=True),
        ),
    ]
